### ISSUE TITLE
[BUG] QueryFeast unable to query user features with INT32_LIST dtype column

### ISSUE THREAD

**Issue by mkumari-ed** [NVIDIA-Merlin/systems#115]
### Bug description
I have a column in my dataset that is multi-hot categorical feature, for example, ['mellon','tokkio documentation','merlin','transformers','data science'] which is a list of keyword searches for a user on confluence. I am using 
![Screen Shot 2022-06-08 at 10 08 26 AM](https://user-images.githubusercontent.com/28987826/172732733-dc7bbed7-2f34-4b7a-b9b7-b82f086b2a39.png)
![Screen Shot 2022-06-08 at 8 23 39 AM](https://user-images.githubusercontent.com/28987826/172732785-2c45ae23-a94a-436d-bd4c-ff331663afec.png)
nvtabular to categorify it and then it transforms into a list of integers. So at the time of feature definition to write to user_features.py, I use `Feature(name="search", dtype=ValueType.INT32_LIST)` in the definition. All this works fine until I use QueryFeast operator to fetch user features from the feature repo. I get a `TypeError: Unsupported dtype ValueType.INT32_LIST, unable to cast ValueType.INT32_LIST to a numpy dtype` 

### Steps/Code to reproduce bug

1.  generate a column of type object but that contains list of string items like what I have mentioned above. Also attaching the screenshot of what my raw data looks like.
2. follow all steps in https://github.com/NVIDIA-Merlin/Merlin/tree/main/examples/Building-and-deploying-multi-stage-RecSys notebooks to reach cell 13 in https://github.com/NVIDIA-Merlin/Merlin/blob/main/examples/Building-and-deploying-multi-stage-RecSys/02-Deploying-multi-stage-RecSys-with-Merlin-Systems.ipynb notebook.

### Environment details
- Merlin version:  22.05 tensorflow-inference container
- Python version: 3.8
- Tensorflow version (GPU?): 2.9.1

**Comment by mkumari-ed** [comment]
@jperez999  Hi Julio, were you able to check on this?

**Comment by karlhigley** [comment]
It's a little difficult to test, but I think #123 will address this issue

**Comment by mkumari-ed** [comment]
@karlhigley and @rnyak
I tested it out with my correct data today. I am attaching all screenshots for visibility. With the list of strings feature(for ex. ['sipl_camera', 'build qnx', 'yuv', 'dl g']), I am unable to materialize the user features using feast. The error that I get is `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`. Also, attaching the user features sample and output of `train_tt.to_ddf().compute()` here along with the snapshot of how the raw data looks like
![materialize user features error](https://user-images.githubusercontent.com/28987826/180262833-ac3ad0d6-3ac0-4338-8dad-c4909649df41.png)
![raw data sample](https://user-images.githubusercontent.com/28987826/180262839-b3fc2df2-de4e-463b-9ef0-fa9b4ec7ed46.png)
![train tt sample](https://user-images.githubusercontent.com/28987826/180262843-f0514d98-29a5-4c04-89a3-736cf13f05a9.png)
![user features sample](https://user-images.githubusercontent.com/28987826/180262844-96b3966e-ed86-4bab-9e0d-b6c4654a7911.png)
