### ISSUE TITLE
[BUG] Exporting Ensemble object in deployment of multi-stage recsys example fails throwing `ValueError: Missing columns ['click/binary_classification_task'] found in operatorSubsetColumns during compute_input_schema.`

### ISSUE THREAD

**Issue by mkumari-ed** [NVIDIA-Merlin/systems#128]
### Bug description

Unable to export ensemble object on my dataset following second notebook for deployment in the multi-stage recsys examples. Even though I have pulled from the latest branches of `models`, `core`, `systems`,`nvtabular` and `Merlin` multiple times and have restarted my inference 22.05 container multiple times to try it out but still keep getting this error.

### Steps/Code to reproduce bug

1.  Download the sample dataset here: https://drive.google.com/drive/u/1/folders/1LjLTVKCESUnE5LQizNVMEpKvfs3A6lI1
2.  Run the cells in the building-recommender-systems notebook and then try running all the cells in second notebook deploying multi-stage recsys until cell 21 where I am getting this error `ValueError: Missing columns ['click/binary_classification_task'] found in operatorSubsetColumns during compute_input_schema.`

### Expected behavior

It used to work before the `output_1` column was renamed to `click/binary_classification_task` with the old code

### Environment details
- Merlin version:  tensorflow-inference container: 22.05
- Platform: Ubuntu 20.04
![Screen Shot 2022-06-28 at 8 23 18 AM](https://user-images.githubusercontent.com/28987826/176597971-3708aa38-eb80-4443-82b5-7f542f3f28ae.png)
![Screen Shot 2022-06-28 at 8 23 34 AM](https://user-images.githubusercontent.com/28987826/176597981-6598c580-4b06-4d1c-902e-44351769ffd2.png)

- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):

**Comment by EvenOldridge** [comment]
@rnyak can you take a look at this when you're back on Monday.  @karlhigley @jperez999  do you have any insights into what might be going on here?

**Comment by mkumari-ed** [comment]
Changing the name to relevant/binary_classification fixed the previous error but now I get a new error for PredictTensorflow operator
![Screen Shot 2022-07-14 at 8 31 03 AM](https://user-images.githubusercontent.com/28987826/179849880-21d7b890-e5a6-4a20-a2bc-807787f057f8.png)

**Comment by mkumari-ed** [comment]
I am able to export ensemble as graph now if I don't keep the list type column and pretrained embeddings in the feature set.
