### ISSUE TITLE
[Task] Update Feast version in the Feast op and example

### ISSUE THREAD

**Issue by karlhigley** [NVIDIA-Merlin/systems#174]
### Description
Revise our Feast operator and example notebooks to be compatible with versions of Feast newer than `0.20`

**Additional context**
The latest Feast version is `0.23.2`, we're still on `0.19.4`

**Comment by viswa-nvidia** [comment]
This dev waits on type conversion

**Comment by nv-alaiacano** [comment]
@oliverholworthy 's [change](https://github.com/feast-dev/feast/blame/v0.27.0/setup.py#L77) to un-pin Dask has been released in Feast 0.27 🎉 . So we should target that version for the update.

**Comment by nv-alaiacano** [comment]
Feast has been updated to 0.31
