### ISSUE TITLE
Investigate what work is required in systems side for serving TF session based models.  What kind of SLA do we need for practical performance.  Under what batch size/data.

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/systems#202]

**Comment by viswa-nvidia** [comment]
@karlhigley , for completing the example in 22.10 , do we need to complete this investigation ? Are we already working on this ?

**Comment by karlhigley** [comment]
There are no models to investigate this with yet AFAIK, so I'd be very surprised if we completed an end-to-end example in 22.10

**Comment by karlhigley** [comment]
I also have no way to independently determine SLAs other than pulling a number out of the air, so the title of this issue doesn't make much sense 😅
