### ISSUE TITLE
[BUG] requirements gpu.txt will install feast == 0.20.0

### ISSUE THREAD

**Issue by zhiruiwang** [NVIDIA-Merlin/systems#203]
### Bug description

[gpu.txt in requirements](https://github.com/NVIDIA-Merlin/systems/blob/main/requirements/gpu.txt#L1) has `feast<=0.20.0`, which means it will install feast == 0.20.0. 

However the current operators only works for 0.19.4

### Steps/Code to reproduce bug

Installing merlin-systems using `pip install merlin-systems[gpu]` will cause Merlin system not able to work with feast operators.

### Expected behavior

The gpu.txt should be changed to `feast<0.20.0`, before the codebase is updated to be compatible with the latest Feast versions.

**Comment by nv-alaiacano** [comment]
Thanks for the catch! This was a typo from when we reorganized the requirements files.
