### ISSUE TITLE
[BUG] Bugs to deploy NVTabular + Transformer4Rec with TorchScript backend

### ISSUE THREAD

**Issue by bschifferer** [NVIDIA-Merlin/systems#257]
### Bug description
We try to fix the NVTabular + Transformer4Rec integration. I run into multiple issues:

1. ValueError: Output column 'session_id' not detected in any child inputs for 'TransformWorkflow'.
When I call `Ensemble(torch_op, workflow.input_schema)` (or `ensemble.export`, not sure which of them), Merlin System checks if every output column is at least consumed as an input before https://github.com/NVIDIA-Merlin/systems/blob/main/merlin/systems/dag/node.py#L119-L123 . However, we have cases, where NVTabular returns output columns, which are not used in the model itself: E.g. session_id, day_first, etc.

We cannot remove columns from the output schema in NVTabular.
Merlin Systems runs a check to ensure that all output columns are relevant.

```
torch_op = workflow.input_schema.column_names >> TransformWorkflow(workflow) >> PredictPyTorch(
    traced_model, input_schema, output_schema
)

ensemble = Ensemble(torch_op, workflow.input_schema)
ens_config, node_configs = ensemble.export(ens_model_path)
```

2. E1207 15:56:49.997184 13273 model_repository_manager.cc:996] Poll failed for model directory 'ensemble_model': output 'next-item' for ensemble 'ensemble_model' is not written

I removed the check in Merlin System and I could export an ensemble. However, I am not able to load the ensemble_model in Triton.

When I start Triton in explicit mode, I am able to load the NVTabular Model and Transformer4Rec model. However, when I try to load `ensemble_model`, I get following error:
```
E1207 15:56:49.997184 13273 model_repository_manager.cc:996] Poll failed for model directory 'ensemble_model': output 'next-item' for ensemble 'ensemble_model' is not written 
```

3. Will the ensemble work?
I am not sure, if the ensemble would work. I checked the config files and it seems that NVTabular provides list features as sparse output and Transformer4Rec expects them as dense representation

NVTabular config.pbtxt
```
output {
  name: "item_id-list__values"
  data_type: TYPE_INT64
  dims: -1
  dims: 1
}
output {
  name: "item_id-list__lengths"
  data_type: TYPE_INT64
  dims: -1
  dims: 1
}
output {
  name: "category-list__values"
  data_type: TYPE_INT64
  dims: -1
  dims: 1
}
output {
  name: "category-list__lengths"
  data_type: TYPE_INT64
  dims: -1
  dims: 1
}
output {
  name: "age_days-list__values"
  data_type: TYPE_FP32
  dims: -1
  dims: 1
}
output {
  name: "age_days-list__lengths"
  data_type: TYPE_INT64
  dims: -1
  dims: 1
}
output {
  name: "weekday_sin-list__values"
  data_type: TYPE_FP32
  dims: -1
  dims: 1
}
output {
  name: "weekday_sin-list__lengths"
  data_type: TYPE_INT64
  dims: -1
  dims: 1
}
```

Transformer4Rec config
```
input {
  name: "age_days-list"
  data_type: TYPE_FP32
  dims: -1
  dims: -1
}
input {
  name: "weekday_sin-list"
  data_type: TYPE_FP32
  dims: -1
  dims: -1
}
input {
  name: "item_id-list"
  data_type: TYPE_INT64
  dims: -1
  dims: -1
}
input {
  name: "category-list"
  data_type: TYPE_INT64
  dims: -1
  dims: -1
}
```

**Comment by karlhigley** [comment]
Re: issues 1 and 2 about workflows outputting columns that aren't used, Triton ensembles have a limitation that all outputs returned by a Triton model *must* be used somewhere else in the ensemble. Ensembles that don't meet this constraint can not be loaded successfully by Triton—that's why Systems has a validation check for this, so it can give you a better error message than Triton does before Triton crashes when trying to load the ensemble.

We've recently moved away from Triton ensembles (and toward our own Python executor code) as the mechanism for combining operators, so we might be able to loosen this restriction. It'll take some work though.

**Comment by karlhigley** [comment]
Re: issue 3 and sparse/dense representations, we have ongoing issues throughout Merlin with how the shapes, sparse/dense, and fixed/ragged properties of fields/features/columns are represented. It's something I'd like to propose a standard for and build into Merlin Core so that all of the Merlin libraries use the same code and the same concepts.

**Comment by rnyak** [comment]
@karlhigley with the current changes in core and dataloader, do you think this bug will be solved?

**Comment by karlhigley** [comment]
I think we're in a much better position to tackle this now, particularly with the work to capture shapes in T4R moving forward 👍🏻

**Comment by karlhigley** [comment]
There's another part to this though, which is something that @oliverholworthy, @jperez999, and I discussed the other day: We have a whole separate way of running NVTabular Workflows at serving time, which changes the output format depending on which modeling framework is expected to consume the data. I think that should go away, through some combination of moving functionality out of it into the graph executors in Core and removing the framework-specific output formats. 

A Workflow is a Workflow, and it should always return the same data in the same format. If we need to adjust the format of the data after the Workflow and before the model, we should accomplish that using additional operators (e.g. padding) instead. Ideally, we'd use exactly the same operators that are used in the dataloaders, which has been one of the goals of a lot of the reworking of Merlin internals we've done lately.

**Comment by karlhigley** [comment]
(One of the reasons we had NVT Workflows returning different formats for different frameworks at serving time was the so-called "scalar shape" issue, where the TF and Torch dataloaders returned differently shaped data for scalar feature columns, which then led to models that expected the same data to be provided in different formats. With the work to add shapes to schemas happening now, we're in the process of sorting that out, but it's going to take some work.)

**Comment by rnyak** [comment]
Recently I tested serving NVT+TorchScript model but I was getting two issues:
- extra columns that are not fed to the model are not liked. As a workaround solution, I could remove them from workflow schema, and I avoided that error.
- Triton was complaining about `__values` even though config files do not include any column with `__values` and `__offsets`.

There were some PRs merged I need to test again if this issue was solved.

**Comment by rnyak** [comment]
New update: I tested serving NVT + Torchscript Model and now the error I get is related to output. Somehow output is expected to be ragged, but it is not, and I think it should not be.

```
Failed to transform operator <merlin.systems.dag.runtimes.triton.ops.pytorch.PredictPyTorchTriton object at 0x7fdec975e790>
Traceback (most recent call last):
  File "/systems/merlin/systems/triton/conversions.py", line 164, in triton_response_to_tensor_table
    values = _array_from_triton_tensor(response, f"{out_col_name}__values")
  File "/systems/merlin/systems/triton/conversions.py", line 201, in _array_from_triton_tensor
    raise ValueError(f"Column {name} not found in {type(triton_obj)}")
ValueError: Column next-item__values not found in <class 'c_python_backend_utils.InferenceResponse'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/merlin/dag/executors.py", line 183, in _transform_data
    output_data = node.op.transform(selection, input_data)
  File "/systems/merlin/systems/dag/runtimes/triton/ops/pytorch.py", line 86, in transform
    return triton_response_to_tensor_table(
  File "/systems/merlin/systems/triton/conversions.py", line 168, in triton_response_to_tensor_table
    outputs_dict[out_col_name] = _array_from_triton_tensor(response, out_col_name)
  File "/systems/merlin/systems/triton/conversions.py", line 201, in _array_from_triton_tensor
    raise ValueError(f"Column {name} not found in {type(triton_obj)}")
ValueError: Column next-item not found in <class 'c_python_backend_utils.InferenceResponse'>
```

**Comment by karlhigley** [comment]
> extra columns that are not fed to the model are not liked. As a workaround solution, I could remove them from workflow schema, and I avoided that error.

This one I believe was addressed by removing the validation, since this is no longer an issue if we don't use Triton's native ensembling mechanism

**Comment by viswa-nvidia** [comment]
@rnyak to link PR and close
