### ISSUE TITLE
[BUG] `prediction_tasks=mm.BinaryOutput(target_column)` doesn't work with `PredictTensorflow`

### ISSUE THREAD

**Issue by radekosmulski** [NVIDIA-Merlin/systems#274]
### Bug description
I build a model with `mm.BinaryOutput` and train it

```
model = mm.DCNModel(
    train_ds.schema,
    depth=2,
    deep_block=mm.MLPBlock([64, 32]),
    prediction_tasks=mm.BinaryOutput(target_column),
)
```

I attempt to export this as a serving operator but when I do I get an error:
![image](https://user-images.githubusercontent.com/2444926/213360553-f5c373fd-4771-49f9-ad81-a79fed7fb96a.png)

To reproduce, run the TF notebooks from this PR: https://github.com/NVIDIA-Merlin/Merlin/pull/779

### Expected behavior
I can serve predictions on Triton from a TF model trained with `mm.BinaryOutput`

### Environment details
22.12 TF container with all repos updated to current main

**Comment by rnyak** [comment]
@radekosmulski guess this issue was resolved. I am closing this ticket for now, but if you want to reopen it, pls do so.
