### ISSUE TITLE
[QST] filtercandidate opt not working for multi-stage workflow

### ISSUE THREAD

**Issue by Tselmeg-C** [NVIDIA-Merlin/systems#281]
# ❓ Questions & Help

## Details

Hi,

I am trying to build up a multi-stage workflow as in the [example ](https://github.com/NVIDIA-Merlin/Merlin/tree/main/examples/Building-and-deploying-multi-stage-RecSys), only with an additional filtering operation (filter out those candidates interacted with users already). The workflow on Triton Inference Server looks like this:
+---------------------------+---------+--------+
| Model                     | Version | Status |
+---------------------------+---------+--------+
| 0_queryfeast              | 1       | READY  |
| 1_predicttensorflowtriton | 1       | READY  |
| 2_queryfaiss              | 1       | READY  |
| 3_filtercandidates        | 1       | READY  |
| 4_queryfeast              | 1       | READY  |
| 5_unrollfeatures          | 1       | READY  |
| 6_predicttensorflowtriton | 1       | READY  |
| 7_softmaxsampling         | 1       | READY  |
| ensemble_model            | 1       | READY  |
+---------------------------+---------+--------+

The TIS server is running, but throwing following error:

> ---------------------------------------------------------------------------
InferenceServerException                  Traceback (most recent call last)

----> response = send_triton_request(request_schema, request, outputs)

File /usr/local/lib/python3.8/dist-packages/merlin/systems/triton/utils.py:193, in send_triton_request(schema, df, outputs_list, client, endpoint, request_id, triton_model)
    191 outputs = [grpcclient.InferRequestedOutput(col) for col in outputs_list]
    192 with client:
--> 193     response = client.infer(triton_model, inputs, request_id=request_id, outputs=outputs)
    195 results = {}
    196 for col in outputs_list:

File /usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py:1431, in InferenceServerClient.infer(self, model_name, inputs, model_version, outputs, request_id, sequence_id, sequence_start, sequence_end, priority, timeout, client_timeout, headers, compression_algorithm)
   1429     return result
   1430 except grpc.RpcError as rpc_error:
-> 1431     raise_error_grpc(rpc_error)

File /usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py:62, in raise_error_grpc(rpc_error)
     61 def raise_error_grpc(rpc_error):
---> 62     raise get_error_grpc(rpc_error) from None

**InferenceServerException: [StatusCode.INVALID_ARGUMENT] in ensemble 'ensemble_model', [request id: 1] unexpected shape for input 'filtered_ids' for model '4_queryfeast'. Expected [-1,1], got [100]**
> ---------------------------------------------------------------------------

The only code-change in the original example notebooks is like following:
`
filtering = retrieval["candidate_ids"] >> FilterCandidates(
    filter_out=user_features["user_id"]
)

item_features = filtering >> QueryFeast.from_feature_view(
    store=feature_store, view="item_features", column="filtered_ids", output_prefix="item",
    include_id=True,
)
`

Could anyone help me out, what did I do wrong?

**Comment by rnyak** [comment]
@Tselmeg-C thanks for reporting the issue.`FilterCandidates` functionality does not currently work as expected, and it is being worked on. Once it is completed we will create an example.
