### ISSUE TITLE
[QST] Get recommended IDs and scores back from TIS at the same time

### ISSUE THREAD

**Issue by Tselmeg-C** [NVIDIA-Merlin/systems#287]
# ❓ Questions & Help

## Details

Hi,

I am trying to build up a multi-stage workflow as in the [example ](https://github.com/NVIDIA-Merlin/Merlin/tree/main/examples/Building-and-deploying-multi-stage-RecSys). The workflow on Triton Inference Server looks like this:
+---------------------------+---------+--------+
| Model | Version | Status |
+---------------------------+---------+--------+
| 0_queryfeast | 1 | READY |
| 1_predicttensorflowtriton | 1 | READY |
| 2_queryfaiss | 1 | READY |
| 3_queryfeast | 1 | READY |
| 4_unrollfeatures | 1 | READY |
| 5_predicttensorflowtriton | 1 | READY |
| 6_softmaxsampling | 1 | READY |
| ensemble_model | 1 | READY |
+---------------------------+---------+--------+

I need the recommended IDs and corresponding scores at the same time, but in this workflow I am receiving only 'ordered_ids' (randomized by softmax step) and if I skip step 6, I will only receive 'buy/binary_classification_task'. How can I receive a list of ordered_ids and their corresponding scores at the same time?

Another question is how can I skip randomization in softmax sampling opt and receive the same results in every request?

Thanks in advance!

**Comment by zhiruiwang** [comment]
I have the same question. It would be great if Merlin-systems can also return scores along with ID's, so we can allow front end to do some further manipulation. 

@Tselmeg-C In terms of bypassing softmax sampling, what I did was **set a very large temperature**(1e5-1e6, but based on the magnitude of the score you are getting, it might change), then the returned results are stable in every request.

**Comment by Tselmeg-C** [comment]
> I have the same question. It would be great if Merlin-systems can also return scores along with ID's, so we can allow front end to do some further manipulation.
> 
> @Tselmeg-C In terms of bypassing softmax sampling, what I did was **set a very large temperature**(1e5-1e6, but based on the magnitude of the score you are getting, it might change), then the returned results are stable in every request.

Thanks for sharing. I will try manipulating the temperature arg, to see if I could get consistent results.

**Comment by karlhigley** [comment]
We've just merged [a PR that makes this possible](https://github.com/NVIDIA-Merlin/systems/pull/290) using the `SoftmaxSampling` operator, which should be included in the upcoming 23.02 release.

As we grow the set of the operators in Merlin Systems a plain top-K operator is on our list of things to add, but for the time being, setting a very large sampling temperature is a reasonable workaround.
