### ISSUE TITLE
[BUG] Error while serving NVT Model on Triton Inference Server

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/systems#31]
**Describe the bug**

I am getting the error below from TIS when loading the models to the server. These columns are not tagged as `continuous` or `categorical` after groupby op and therefore their proper tags are missing in the workflow.output_schema and  there are more output columns produced by the workflow than are in cats and conts. This is causing the issue. 

Would `AddMetadata` op solve the issue if we add it after groupby op and tag these columns as `continuous`?

| Model           | Version | Status                                                                                                                                                                        |
+-----------------+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t4r_pytorch_nvt | 1       | UNAVAILABLE: Internal: ValueError: The following extra columns were found in the workflow's output: {'timestamp/weekday/sin-list_trim', 'day-first', 'timestamp/age_days-list |
|                 |         | _trim'}                                                                                                                                                                       |
|                 |         |                                                                                                                                                                               |
|                 |         | At:                                                                                                                                                                           |
|                 |         |   /nvtabular/nvtabular/inference/workflow/base.py(70): __init__                                                                                                               |
|                 |         |   /nvtabular/nvtabular/inference/workflow/tensorflow.py(33): __init__                                                                                                         |
|                 |         |   /workspace/models_new/t4r_pytorch_nvt/1/model.py(85): initialize                                                                                                            |
| t4r_pytorch_pt  | 1       | READY   

**Steps/Code to reproduce bug**
The code can be reproduced by running the [getting started notebooks](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/getting-started-session-based/02-session-based-XLNet-with-PyT.ipynb) in Transformers4Rec repo. Add this script after model training:

```
import nvtabular as nvt
workflow = nvt.Workflow.load('workflow_etl')
from nvtabular.inference.triton import export_pytorch_ensemble
export_pytorch_ensemble(
    model,
    workflow,
    sparse_max=trainer.get_train_dataloader().dataset.sparse_max,
    name= "t4r_pytorch",
    model_path= "/workspace/models",
    label_columns =[],
)
```
**Expected behavior**
No error should occur when we load models to TIS. 

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of NVTabular install: [conda, Docker, or from source]: DOCKER
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
 
Using `docker-pytorch-inference:22.03`  wit the latest NVTabular main branch pulled.

**Additional context**

**Comment by karlhigley** [comment]
Wonder if this is related to https://github.com/NVIDIA-Merlin/NVTabular/pull/1424
