### ISSUE TITLE
[BUG] NVT Categorify category files aren't saved/loaded to the correct path

### ISSUE THREAD

**Issue by karlhigley** [NVIDIA-Merlin/systems#312]
### Bug description

```
FileNotFoundError: [Errno 2] No such file or directory: './/categories/unique.city_id.parquet'
```

### Steps/Code to reproduce bug

Run this notebook: https://github.com/NVIDIA-Merlin/models/blob/fix_datetime_issue_add_inference_on_TIS/examples/usecases/transformers-next-item-prediction-single-column.ipynb

NVTabular Categorify ops try to read the mapping table unique.city_id.parquet  - The categories folder is not exported to the triton artifacts for me. However, even if they would be copied, I noticed that it tried to find the categories folder in the directory, where I started triton. As I started it in /opt/tritonserver , I had to copy categories to /opt/tritonserver manually to fix it.

### Expected behavior

Categorify should work in when executing Workflows in Triton

### Additional context

Surfaced while trying to make TF session-based serving work

**Comment by angmc** [comment]
The notebook listed is missing? 404
