### ISSUE TITLE
Have a padding operator and add Support for ragged inputs  that we can use consistently with Transformers for rec

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/systems#322]

**Comment by oliverholworthy** [comment]
Support for ragged inputs in Transformers4Rec added in https://github.com/NVIDIA-Merlin/Transformers4Rec/pull/666

**Comment by oliverholworthy** [comment]
Tested with NVT workflow with ragged outputs and model with ragged inputs here: https://github.com/NVIDIA-Merlin/Transformers4Rec/pull/677

Using a Padding Operator also works in between NVT Workflow and Transformers4Rec
