### ISSUE TITLE
[DOC]Update the instructions to build the docs 

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/systems#68]
Update the instructions to build the docs in here. https://github.com/NVIDIA-Merlin/systems/tree/main/docs 
Looks like it was copy pasted from `models`?

Impact: L

**Comment by mikemckiernan** [comment]
I happened to update the `docs/README.md` file while adding the docs build.

https://github.com/NVIDIA-Merlin/systems/pull/77/files#diff-0b5ca119d2be595aa307d34512d9679e49186307ef94201e4b3dfa079aa89938

Closing.
