### ISSUE TITLE
[DOC] Docs rendering didn’t pick up the changes 

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/systems#69]
Julio reported this with XL impact during the Doc string bash

**Comment by viswa-nvidia** [comment]
We can't generate docs locally. This is a blocker for the dev process and not the 22.04 release. Can we standup docs on Github pages for Systems by 22.04 - Curently its 404 @mikemckiernan  to check with @benfred

**Comment by mikemckiernan** [comment]
I can't explain why anyone had any difficulty generating the docs locally.

For the second issue, the 404, the foll PR coincidentally addresses the concern: https://github.com/NVIDIA-Merlin/systems/pull/77
