### ISSUE TITLE
[DOC]Systems Docstring bash for v1.0 

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/systems#72]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-ecb2d4d5-7fff-a53e-8ac5-20b115edd4f7"><div dir="ltr" style="margin-left:0pt;" align="left">

Issue | Reported By | Impact | Owner | Status
-- | -- | -- | -- | --
Update the instructions to build the docs in here. https://github.com/NVIDIA-Merlin/systems/tree/main/docs Looks like it was copy pasted from `models`? | Ronay | L |   |  
Docs rendering didn’t pick up the changes | Julio | XL |   |  

</div></b>

- [x] #68 
- [x] #69

**Comment by mikemckiernan** [comment]
I believe the issues are addressed.  Closing.
