### ISSUE TITLE
[BUG]  run_triton_server() func does not launch the TIS

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/systems#87]
### Bug description

At the last step of the  `02-Deploying-multi-stage-RecSys-with-Merlin-Systems.ipynb` notebook, I run `run_triton_server(export_path)` but this does not launch TIS. Based on `run_triton_server` func definition, it is returning the `client` object but it is not clear how returned `client` object is used in `send_triton_request()` func to be able to sent the request to running server.

Please see error  showing that ``run_triton_server(export_path)` does not launch TIS:

```
# create a request to be sent to TIS
from merlin.core.dispatch import make_df
from merlin.systems.triton.utils import run_triton_server
from merlin.systems.triton.utils import send_triton_request
from merlin.core.dispatch import get_lib

request = make_df({"user_id": [1]})
request["user_id"] = request["user_id"].astype(np.int32)
run_triton_server(export_path)
outputs = ensemble.graph.output_schema.column_names
output = send_triton_request(request, outputs)

---------------------------------------------------------------------------
InferenceServerException                  Traceback (most recent call last)
Input In [49], in <cell line: 14>()
     10 run_triton_server(export_path)
     12 outputs = ensemble.graph.output_schema.column_names
---> 14 output = send_triton_request(request, outputs)

File /systems/merlin/systems/triton/utils.py:132, in send_triton_request(df, outputs_list, endpoint, request_id, triton_model)
    129 except Exception as e:
    130     raise e
--> 132 if not triton_client.is_server_live():
    133     raise ValueError("Client could not establish commuincation with Triton Inference Server.")
    135 inputs = triton.convert_df_to_triton_input(df.columns, df, grpcclient.InferInput)

File /usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py:302, in InferenceServerClient.is_server_live(self, headers)
    300     return response.live
    301 except grpc.RpcError as rpc_error:
--> 302     raise_error_grpc(rpc_error)

File /usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py:62, in raise_error_grpc(rpc_error)
     61 def raise_error_grpc(rpc_error):
---> 62     raise get_error_grpc(rpc_error) from None

InferenceServerException: [StatusCode.UNAVAILABLE] failed to connect to all addresses
​
```

It doesn't look like `send_triton_request` accepts a client object? It'd be nice to have example of how these functions work together? 

### Steps/Code to reproduce bug

Please run the notebooks `01` and `02` in here [Deploying-multi-stage-RecSys](https://github.com/NVIDIA-Merlin/Merlin/tree/main/examples/Deploying-multi-stage-RecSys) to repro the issue.

### Environment details
- Merlin version: 
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):

`merlin-tensorflow-inference:22.04` with the latest main branches pulled.

**Comment by jperez999** [comment]
So the tritonserver/send_triton_request combo is meant to work separately. You should be starting a tritonserver on the command line and then connecting to that server using the send_triton_request. You used the endpoint kwarg for the send_triton_request only if you did not spawn the tritonserver on the default endpoint. Please refer to https://github.com/NVIDIA-Merlin/systems/blob/main/examples/Getting_Started/Serving-Ranking-Models-With-Merlin-Systems.ipynb to see how it should be used.
