### ISSUE TITLE
[FEA] Add NVT model to ensemble DAG of the multi-stage-recsys pipeline to send raw data as a request to TIS

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/systems#99]
# 🚀 Feature request

Currently in our deploying-multi-stage RecSys example,  ensemble DAG does not have NVT model. So, we send processed data as a request to TIS, not the raw data.  It'd be very useful to add NVT model to the ensemble DAG and get it loaded to TIS as well, to realize an end-to-end pipeline.

**Comment by rnyak** [comment]
@karlhigley I am adding this to 23.06 since I did not get a chance to test this, instead I was testing serving TT model with list inputs.

**Comment by karlhigley** [comment]
Cool, sounds good! Thanks for updating the milestone, and we'll get to it when we can.

**Comment by rnyak** [comment]
closing since this was added to the example nbs.
